version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: funk-radio-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: funkradio
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - funk-radio-network

  app:
    build: .
    container_name: funk-radio-app
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/funkradio
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - funk-radio-network

  # Serviço de desenvolvimento
  dev-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: funk-radio-dev
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/funkradio
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/server/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - funk-radio-network
    profiles:
      - dev

volumes:
  mongodb_data:

networks:
  funk-radio-network:
    driver: bridge