services:
  - type: web
    name: funk-radio-2025
    env: node
    buildCommand: npm install && cd server && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production